[project]
name = "airbnb_webscraper"
version = "4.6.0"
description = "Web scraper for Airbnb listings and pricing data"
authors = ["Simon Salamian <simonsalamian@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/username/airbnb-webscraper"
repository = "https://github.com/username/airbnb-webscraper"
keywords = ["airbnb", "scraper", "webscraper", "data"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W"]
ignore = ["E501"]

[custom_config]
# Currency code to use for pricing and display
currency = "GBP"

# Label for the location being scraped (optional; if None the script will ask for this information)
location_label = "Heidelberg"

# Copy and paste your search link from the browser when on Airbnb.com.
# (optional; if None the script will ask for this link)
airbnb_mapsearch_URL = "https://www.airbnb.com/s/Heidelberg/homes?refinement_paths%5B%5D=%2Fhomes&checkin=2025-10-06&checkout=2025-10-10&date_picker_type=calendar&adults=2&guests=2&search_type=user_map_move&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-11-01&monthly_length=3&monthly_end_date=2026-02-01&price_filter_input_type=2&price_filter_num_nights=4&channel=EXPLORE&zoom_level=12.020105491743175&acp_id=ce7e0b7a-6a93-407c-890f-0fcea0783f5d&source=structured_search_input_header&place_id=ChIJzdzMDgXBl0cR1zokRADq5u8&query=Heidelberg&search_mode=regular_search&ne_lat=49.485912066132514&ne_lng=8.759427434538566&sw_lat=49.32221802075744&sw_lng=8.538927188078134&zoom=12.020105491743175&search_by_map=true"

# Which additional APIs to call. The more requests, the longer the web scrape takes
scrape_calendar = true
scrape_weekly_pricing = true
scrape_description = true
translate_description_to_English = true
scrape_reviews = true

# Open the resulting CSV files automatically after the scraping finishes
open_csv_on_completion = true

# Logging level for script output (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_level = "INFO"
